#!/bin/bash

PACMAN="Updating installed packages hosted in official repositories"
echo -e "\033[1;37m${PACMAN}\033[0;39m"
pacmatic -Syu
echo

mapfile -t UNNEEDED_PKGS < <(pacman -Qdttq)
if [ ! "${UNNEEDED_PKGS[*]}" = "" ]; then
	UNNEEDED="Removing unneeded packages found by 'pacman -Qdttq'"
	echo -e "\033[1;37m${UNNEEDED}\033[0;39m"
	pacman -Rscnu "${UNNEEDED_PKGS[@]}"
	echo
fi

CACHE="Removing package caches"
echo -e "\033[1;37m${CACHE}\033[0;39m"
yes | pacman -Scc
echo
