#!/bin/bash

MSG="Update installed packages managed by git"
echo -e "\033[1;37m${MSG}\033[0;39m"
yay --answerclean All \
    --answerdiff Installed \
    --answeredit All \
    -S $(pacman -Qqm | grep -- '-git$')

# vim:set ts=2 sw=2 et:
