#!/bin/bash

OWNER=nosada

REFLECTOR="Generating /etc/pacman.d/mirrorlist by reflector to find fastest mirror"
echo -e "\033[1;37m${REFLECTOR}\033[0;39m"
reflector --age 12 --sort age --country $(where-am-i) --save /etc/pacman.d/mirrorlist
TOP_MIRROR=$(grep Server /etc/pacman.d/mirrorlist | head -1 | awk '{print $3}')
echo "Chosen mirror: $TOP_MIRROR"

PACMAN="Updating installed packages hosted in official repositories"
echo -e "\033[1;37m${PACMAN}\033[0;39m"
pacmatic -Syu
echo

UNNEEDED_PKGS=$(pacman -Qdttq)
if [ ! "$UNNEEDED_PKGS" = "" ]; then
	UNNEEDED="Removing unneeded packages found by 'pacman -Qdttq'"
	echo -e "\033[1;37m${UNNEEDED}\033[0;39m"
	pacman -Rscnu $UNNEEDED_PKGS
	echo
fi

CACHE="Removing package caches"
echo -e "\033[1;37m${CACHE}\033[0;39m"
pacman --noconfirm -Scc
echo
